### ISSUE TITLE
whiteboard images from discussion

### ISSUE THREAD

**Issue by shiffman** [ml5js/ml5-website#1]
![img_6120](https://user-images.githubusercontent.com/191758/52501986-a04a3600-2baf-11e9-95f8-c1803bcbc995.jpg)
![img_6121](https://user-images.githubusercontent.com/191758/52501988-a04a3600-2baf-11e9-9cd1-0d80429a681c.jpg)
![img_6122](https://user-images.githubusercontent.com/191758/52501989-a04a3600-2baf-11e9-969a-c54a227288fa.jpg)
![img_6123](https://user-images.githubusercontent.com/191758/52501990-a04a3600-2baf-11e9-981b-1d211ddfaa3c.jpg)

**Comment by joeyklee** [comment]
![ml5-universe](https://user-images.githubusercontent.com/3622055/52509061-c4fcd880-2bc4-11e9-8a9d-59d11ca49645.png)

**Comment by bomanimc** [comment]
Really cool to see the early thinking here on ml5.js! Closing this issue, but glad that these conversations/ideas were logged!
